/**
 * PVCS — turn on "review and resubmit" for the shift request forms.
 * Written 2026-08-15.
 *
 * WHAT THIS DOES
 *   For each form listed in FORMS below it sets:
 *     - collect email addresses  (so a receipt can be sent)
 *     - allow response editing   (the receipt carries an "Edit response" link)
 *   An edited response OVERWRITES the same row in the responses sheet — it does
 *   not append a second row, so there is nothing to de-duplicate.
 *
 * WHAT THIS CANNOT DO
 *   "Send responders a copy of their response" has NO Apps Script method.
 *   For EACH form, open it and set it by hand, once:
 *       Settings tab > Responses > Send responders a copy of their response > Always
 *   While you are there, confirm "Collect email addresses" reads
 *   "Responder input" and not "Verified" — Verified forces a Google sign-in
 *   that work accounts may not have.
 *
 * HOW TO RUN
 *   Paste into any authorized Apps Script project owned by
 *   doctormikeharrington@gmail.com (the psychiatrist form's bound project works),
 *   select enableAll, click Run, then read the log.
 *
 * WARNING — READ BEFORE RUNNING ON A FORM THAT ALREADY HAS RESPONSES
 *   Turning on email collection adds an "Email Address" column to the linked
 *   responses sheet. Any script that reads that sheet by column POSITION can
 *   break. This matters for the psychiatrist form: the v4 on-call scheduler
 *   reads the responses sheet. After running this, generate a test schedule
 *   (runSampleTest / generateSchedule) and confirm the output still looks right
 *   BEFORE the real round. The PA and resident scripts are unaffected —
 *   their schedules are generated by hand from the sheet.
 */

var FORMS = [
  {
    label: 'Psychiatrist on-call requests — Nov 9 2026 to Jan 3 2027',
    id: '1bvojJ3zQLJTN_1nUxp2vVK3KL6gQuU9aysSG52jtoU8'
  },
  {
    label: 'PA additional shifts — Nov–Dec 2026',
    id: '19vz74w8rK4Qfc-5yTocrd124MHb77ces9dDlqtg28R8'
  },
  {
    label: 'Resident extra shifts — Sep–Oct 2026 (round closed; next round inherits the setting from resident-shift-form.gs)',
    id: '1-0T-MrIuiH_fVjn7ch1bnggYcfuI5HXve-liOJDb-m8'
  }
];

function enableAll() {
  for (var i = 0; i < FORMS.length; i++) {
    var f = FORMS[i];
    try {
      var form = FormApp.openById(f.id);
      setResponseEditSettings_(form);
      Logger.log(f.label + '\n    collect email: ' + form.collectsEmail() +
                 ' | allow edits: ' + form.canEditResponse() +
                 '\n    STILL TO DO BY HAND: Settings > Responses > "Send responders a copy" = Always');
    } catch (e) {
      Logger.log(f.label + '\n    FAILED: ' + e.message);
    }
  }
}

/**
 * Shared helper — also used by pa-shift-request-form-nov-dec.gs and
 * resident-shift-form.gs. setEmailCollectionType() is the newer method and is
 * the one that gives "Responder input"; older projects only have
 * setCollectEmail(), which may land on "Verified" — check it in the UI.
 */
function setResponseEditSettings_(form) {
  try {
    form.setEmailCollectionType(FormApp.EmailCollectionType.RESPONDER_INPUT);
  } catch (e) {
    form.setCollectEmail(true);
  }
  form.setAllowResponseEdits(true);
}
